INSERT INTO users (name, email, password, role, created_at, updated_at) VALUES 
	("Athams", "AthamsGamePlayClashOfClans@gmail.com", "$2a$10$oGuu8nG7kpDeS./E3rMY1OIZgtj8bgE5G6Kt9zDBUWNeL7Px.4AFu", "BUYER", NOW(), NOW());

INSERT INTO categories (name) VALUES 
    ("Sementes"),            
    ("Fertilizantes"),        
    ("Irrigação"),               
    ("Ferramentas"),  
    ("Máquinas"), 
    ("Nutrição Animal"),             
    ("Biológicos"),         
    ("Estruturas"),              
    ("Equipamentos Agrícolas"),
    ("Infraestrutura Rural");   

INSERT INTO brands (name) VALUES
	("AgroTech"),
	("BioSolo"),
	("TratoRural"),
	("Pulverize"),
	("SoloFértil"),
	("NutriBov"),
	("Sementes Brasil"),
	("AgroMaq"),
	("BioFix"),
	("CercaFácil"),
	("IrrigaPro"),
	("AgriHouse");
    
INSERT INTO products (name, description, price, rating, stock, category_id, brand_id, created_at, updated_at) VALUES
	("Semente de Milho Híbrido", "Alta produtividade, resistente a pragas", 299.90, 4.6, 500, 1, 1, NOW(), NOW()),
	("Adubo Orgânico Premium", "Fertilizante natural para hortas e plantações", 89.50, 4.7, 1200, 2, 2, NOW(), NOW()),
	("Trator Agrícola TRX-500", "Trator com 75cv, ideal para cultivo em larga escala", 25000.00, 4.9, 1, 5, 3, NOW(), NOW()),
	("Pulverizador Costal 20L", "Pulverizador manual para aplicação de defensivos", 199.90, 4.3, 300, 9, 4, NOW(), NOW()),
	("Calcário Dolomítico", "Corretivo de solo para controle de acidez", 45.00, 4.2, 1000, 2, 5, NOW(), NOW()),
	("Ração para Gado Leiteiro", "Ração balanceada com alto teor energético", 119.90, 4.5, 750, 6, 6, NOW(), NOW()),
	("Semente de Soja RR", "Semente resistente a herbicidas, alta germinação", 349.00, 4.6, 420, 1, 7, NOW(), NOW()),
	("Roçadeira Lateral Gasolina", "Equipamento para corte de mato em terrenos rurais", 899.90, 4.4, 55, 4, 8, NOW(), NOW()),
	("Inoculante Biológico", "Produto microbiológico para fixação de nitrogênio", 79.90, 4.1, 600, 7, 9, NOW(), NOW()),
	("Arame Farpado 500m", "Ideal para cercas rurais", 269.90, 4.2, 180, 10, 10, NOW(), NOW()),
	("Sistema de Irrigação por Gotejamento", "Kit completo para irrigação eficiente", 1599.00, 4.8, 35, 3, 11, NOW(), NOW()),
	("Estufa Agrícola Modular", "Estrutura para cultivo protegido", 5999.00, 4.7, 10, 8, 12, NOW(), NOW()),
    ("Enxada", "Ideal para preparo de solo em pequenas lavouras", 79.90, 4.5, 250, 4, 1, NOW(), NOW()),
	("Controle Biológico de Pulgões", "Solução ecológica para pragas comuns em hortas", 89.90, 4.3, 180, 7, 9, NOW(), NOW()),
	("Suplemento Mineral para Bovinos", "Balanceamento mineral completo para ganho de peso", 59.50, 4.6, 300, 6, 6, NOW(), NOW()),
	("Plantadeira de Precisão 2 Linhas", "Eficiência e regularidade no plantio direto", 23500.00, 4.8, 6, 5, 8, NOW(), NOW()),
	("Aspersor Giratório de Impacto", "Cobertura uniforme para grandes áreas", 149.00, 4.4, 500, 3, 11, NOW(), NOW()),
	("Semente de Feijão Carioca", "Alta produtividade e excelente coloração", 129.90, 4.7, 380, 1, 7, NOW(), NOW()),
	("Fertilizante NPK 20-20-20", "Fertilizante completo para diversas culturas", 99.90, 4.6, 1000, 2, 5, NOW(), NOW()),
	("Carreta Agrícola Basculante", "Transporte seguro de insumos e colheitas", 8750.00, 4.5, 8, 9, 3, NOW(), NOW()),
	("Galpão Agrícola Pré-Moldado", "Estrutura resistente para armazenamento de maquinário", 28990.00, 4.7, 2, 8, 12, NOW(), NOW()),
	("Portão de Aço para Curral", "Alta durabilidade com fechamento seguro", 1299.90, 4.3, 45, 10, 10, NOW(), NOW());

INSERT INTO reviews (rating, comment, user_id, product_id, created_at, updated_at) VALUES
	(5, 'Produção aumentou bastante com essas sementes!', 1, 1, NOW(), NOW()),
	(4, 'Boa germinação, mas poderia ter mais resistência à seca.', 1, 1, NOW(), NOW()),
	(5, 'Excelente qualidade, milho bem desenvolvido.', 1, 1, NOW(), NOW()),
	(5, 'Minhas hortas estão muito mais saudáveis!', 1, 2, NOW(), NOW()),
	(4, 'Bom adubo, cheiro forte mas funciona.', 1, 2, NOW(), NOW()),
	(5, 'Resultado visível em poucos dias, recomendo.', 1, 2, NOW(), NOW()),
	(5, 'Máquina robusta, excelente para grandes áreas.', 1, 3, NOW(), NOW()),
	(5, 'Vale o investimento, trabalha muito bem.', 1, 3, NOW(), NOW()),
	(4, 'Muito bom, mas faltou manual em português.', 1, 3, NOW(), NOW()),
	(4, 'Bom custo-benefício, faz o trabalho.', 1, 4, NOW(), NOW()),
	(3, 'Funciona, mas o encaixe da alça é desconfortável.', 1, 4, NOW(), NOW()),
	(5, 'Leve e prático, uso semanalmente.', 1, 4, NOW(), NOW()),
	(4, 'Melhorou o solo em pouco tempo.', 1, 5, NOW(), NOW()),
	(5, 'Produto de qualidade, ótimo para pasto.', 1, 5, NOW(), NOW()),
	(4, 'Entrega rápida e produto eficiente.', 1, 5, NOW(), NOW()),
	(5, 'Gado com mais energia e produção de leite subiu.', 1, 6, NOW(), NOW()),
	(4, 'Boa ração, mas o preço poderia ser melhor.', 1, 6, NOW(), NOW()),
	(5, 'Excelente balanceamento nutricional.', 1, 6, NOW(), NOW()),
	(5, 'Germinação excelente e resistente aos herbicidas.', 1, 7, NOW(), NOW()),
	(4, 'Cresceu bem, mas tive que reforçar a irrigação.', 1, 7, NOW(), NOW()),
	(5, 'Produto top para produção de soja.', 1, 7, NOW(), NOW()),
	(4, 'Potente, corta bem mesmo vegetação alta.', 1, 8, NOW(), NOW()),
	(3, 'Boa máquina, mas vibra bastante.', 1, 8, NOW(), NOW()),
	(5, 'Fácil de ligar e manusear, ótimo investimento.', 1, 8, NOW(), NOW()),
	(4, 'Ajuda bastante no desenvolvimento das plantas.', 1, 9, NOW(), NOW()),
	(3, 'Demora para ver resultado, mas parece funcionar.', 1, 9, NOW(), NOW()),
	(5, 'Uso sempre, excelente para soja e feijão.', 1, 9, NOW(), NOW()),
	(4, 'Arame forte e fácil de instalar.', 1, 10, NOW(), NOW()),
	(3, 'Bom material, mas veio com um pequeno defeito.', 1, 10, NOW(), NOW()),
	(5, 'Resistente e ótimo para cercar áreas grandes.', 1, 10, NOW(), NOW()),
	(5, 'Economizei muita água e aumentei a produção.', 1, 11, NOW(), NOW()),
	(5, 'Sistema bem completo e fácil de montar.', 1, 11, NOW(), NOW()),
	(4, 'Funcionou bem, mas faltou uma peça na entrega.', 1, 11, NOW(), NOW()),
	(5, 'Estufa resistente e mantém ótima temperatura.', 1, 12, NOW(), NOW()),
	(5, 'Fácil montagem, material de primeira.', 1, 12, NOW(), NOW()),
	(4, 'Boa estrutura, mas o frete foi caro.', 1, 12, NOW(), NOW()),
	(5, 'Muito resistente e bem balanceada.', 1, 13, NOW(), NOW()),
	(4, 'Cabo confortável, uso diário na roça.', 1, 13, NOW(), NOW()),
	(5, 'Eliminou os pulgões sem prejudicar as plantas.', 1, 14, NOW(), NOW()),
	(4, 'Produto ecológico e eficaz.', 1, 14, NOW(), NOW()),
	(5, 'Gado mais saudável e com melhor ganho de peso.', 1, 15, NOW(), NOW()),
	(4, 'Ótimo custo-benefício, recomendo.', 1, 15, NOW(), NOW()),
	(5, 'Precisão excelente no plantio. Alta performance.', 1, 16, NOW(), NOW()),
	(4, 'Fácil de operar e com bom rendimento.', 1, 16, NOW(), NOW()),
	(5, 'Cobertura ampla e regulagem simples.', 1, 17, NOW(), NOW()),
	(4, 'Material resistente e leve.', 1, 17, NOW(), NOW()),
	(5, 'Feijão com excelente rendimento.', 1, 18, NOW(), NOW()),
	(4, 'Boa germinação e crescimento uniforme.', 1, 18, NOW(), NOW()),
	(5, 'Melhora visível em poucos dias.', 1, 19, NOW(), NOW()),
	(4, 'Usado em minha horta e adorei o resultado.', 1, 19, NOW(), NOW()),
	(5, 'Perfeita para transporte de silagem.', 1, 20, NOW(), NOW()),
	(4, 'Construção robusta, recomendo.', 1, 20, NOW(), NOW()),
	(5, 'Muito espaço e estrutura firme.', 1, 21, NOW(), NOW()),
	(5, 'Ideal para guardar maquinário.', 1, 21, NOW(), NOW()),
	(4, 'Fácil de instalar e resistente.', 1, 22, NOW(), NOW()),
	(3, 'Veio com um pequeno amassado, mas funcional.', 1, 22, NOW(), NOW());

INSERT INTO images (url, product_id) VALUES
	('../../public/images/milho1.png', 1),
    ('../../public/images/milho2.png', 1),
    ('../../public/images/milho3.png', 1),
	('../../public/images/fertilizante1.png', 2),
    ('../../public/images/fertilizante2.png', 2),
    ('../../public/images/fertilizante3.png', 2),
    ('../../public/images/fertilizante4.png', 2),
	('../../public/images/trator1.png', 3),
    ('../../public/images/trator2.png', 3),
    ('../../public/images/trator3.png', 3),
    ('../../public/images/trator4.png', 3),
	('../../public/images/pulverizador1.png', 4),
    ('../../public/images/pulverizador2.png', 4),
	('../../public/images/calcário1.png', 5),
    ('../../public/images/calcário2.png', 5),
	('../../public/images/ração1.png', 6),
    ('../../public/images/ração2.png', 6),
	('../../public/images/soja1.png', 7),
    ('../../public/images/soja2.png', 7),
	('../../public/images/roçadeira1.png', 8),
	('../../public/images/inoculante1.png', 9),
    ('../../public/images/inoculante2.png', 9),
	('../../public/images/arame1.png', 10),
    ('../../public/images/arame2.png', 10),
	('../../public/images/gotejamento1.png', 11),
    ('../../public/images/gotejamento2.png', 11),
	('../../public/images/estufa1.png', 12),
    ('../../public/images/estufa2.png', 12),
    ('../../public/images/estufa3.png', 12);